#pragma once

#include <string>
#include "cloud/webservice_api.hpp"

namespace app::cloud {

/**
 * @brief Handles device pairing with backend server
 * 
 * Device Claiming Flow:
 * 1. User gets Hardware ID and Device Password from device label
 * 2. User enters these into web interface, which generates a 6-letter PIN
 * 3. User enters PIN into device's setup portal along with Wi-Fi credentials
 * 4. Device calls DeviceClaimClient::Claim() with hw_id and pin
 * 5. Server validates PIN (10-minute validity window) and binds device to user's account
 * 6. Device begins normal telemetry/long-poll operations
 */
class DeviceClaimClient {
public:
    DeviceClaimClient() = default;
    ~DeviceClaimClient() = default;

    /**
     * @brief Result of a claim operation
     */
    enum class ClaimResult {
        kSuccess,              ///< Device successfully claimed
        kApiCallFailed,        ///< Web service call failed
        kInvalidPin,           ///< PIN invalid or expired (> 10 minutes)
        kAlreadyClaimed,       ///< Device already bound to another user
        kParseError,           ///< Failed to parse server response
        kInvalidParam,         ///< Invalid hw_id or pin parameter
    };

    /**
     * @brief Attempt to claim this device with a web-generated PIN
     * 
     * @param hw_id Hardware ID from device label (e.g., "ERMA-001")
     * @param pin 6-character PIN generated by web interface (e.g., "XRB9L2")
     * @param server_url Optional custom server URL (defaults to aqua.erma.sk)
     * @return ClaimResult indicating success or failure reason
     */
    static ClaimResult Claim(const std::string& hw_id, const std::string& pin,
                            const std::string& server_url = "");

    /**
     * @brief Get human-readable error message
     */
    static const char* ResultToString(ClaimResult result);

private:
    static constexpr const char* kDefaultClaimUrl = "https://aqua.erma.sk/api/device_claim.php";
};

} // namespace app::cloud
